#!/usr/bin/python
 
#  MIT License
#  
#  Copyright (c) 2026 mmkns
#  
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#  
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
 

import sys
import argparse
from xml.dom import minidom


#################################
# utilities
#################################

def open_infile(filename):
  if filename:
    try:
      return open(filename)
    except Exception as e:
        sys.exit(f"Could not open input file: {e}")
  else:
    return sys.stdin

def open_outfile(filename):
  if filename:
    try:
      return open(filename, 'w', encoding="utf-8")
    except Exception as e:
        sys.exit(f"Could not open output file: {e}")
  else:
    return sys.stdout

def stderr(msg):
  print(msg, file=sys.stderr)

valid_chars = frozenset("-0123456789.,MmLlHhVvCcSsQqTtAaZz \n")

def read_path_src(filename):
  try:
    with open(filename) as f:
      data = f.read()
  except Exception as e:
      sys.exit(f"Could not open turtle path data file: {e}")

  if len(frozenset(data).difference(valid_chars)):
    sys.exit(f"Error: File '{filename}' contains invalid SVG path data")

  return data.strip();

#################################
# command line arguments
#################################

parser = argparse.ArgumentParser(prog="svg_path_turtle_compositor",
                                 description="Compile SvgPathTurtle files to SVG")

parser.add_argument("input_file", default="", nargs='?',
                        help="A Turtle SVG file (default is stdin)")

parser.add_argument("output_file", default="", nargs='?',
                        help="A regular SVG file (default is stdout)")

parser.add_argument("-i", "--in-place", action="store_true", default=False,
                        help="Allow overwriting of input file")

parser.add_argument("-a", "--attribute-name", default="src", nargs='?',
                        help="Override 'src' attribute name")

args = parser.parse_args()

#################################
# main
#################################

attrname = args.attribute_name

if args.input_file == args.output_file:
  if args.input_file and not args.in_place:
    sys.exit("To overwrite the input file, use -i/--in-place")

try:
  with open_infile(args.input_file) as infile:
    doc = minidom.parseString(infile.read())

  for e in doc.getElementsByTagName("path"):
    if e.hasAttribute(attrname):
      e.setAttribute("d", read_path_src(e.attributes[attrname].value))
      e.removeAttribute(attrname)

  with open_outfile(args.output_file) as outfile:
    outfile.write(doc.toxml())
    outfile.write("\n")
except Exception as e:
    sys.exit(f"Error: {e}")
